name: Deploy Rust Yew App
on:
  push:
    paths:
      - 'webapp/*'
    branches: 
      - test
      - prod
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set environment
      id: env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
          echo "bucket=${{ secrets.PROD_S3_BUCKET }}" >> $GITHUB_OUTPUT
          echo "distribution=${{ secrets.PROD_CF_DISTRIBUTION }}" >> $GITHUB_OUTPUT
        else
          echo "environment=test" >> $GITHUB_OUTPUT
          echo "bucket=${{ secrets.TEST_S3_BUCKET }}" >> $GITHUB_OUTPUT
          echo "distribution=${{ secrets.TEST_CF_DISTRIBUTION }}" >> $GITHUB_OUTPUT
        fi

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        target: wasm32-unknown-unknown

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Install trunk
      run: |
        wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
        sudo mv trunk /usr/local/bin/
    
    - name: Build Yew Project
      working-directory: ./webapp
      run: |
        trunk build --release
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Upload to S3
      working-directory: ./webapp
      run: |
        echo "Deploying to ${{ steps.env.outputs.environment }} environment..."
        aws s3 sync dist/ s3://${{ steps.env.outputs.bucket }} --delete

    - name: Invalidate CloudFront Distribution
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ steps.env.outputs.distribution }} \
          --paths "/*"
