name: Deploy Rust Yew App

on:
  push:
    branches: 
      - test
      - prod

env:
  CARGO_TERM_COLOR: always
  WORKING_DIRECTORY: ./webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    # Add environment detection
    steps:
    - name: Set environment
      id: env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
          echo "bucket=${{ secrets.PROD_S3_BUCKET }}" >> $GITHUB_OUTPUT
        else
          echo "environment=test" >> $GITHUB_OUTPUT
          echo "bucket=${{ secrets.TEST_S3_BUCKET }}" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
    
    - name: Install trunk
      run: |
        cargo install trunk
        cargo install wasm-bindgen-cli

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/webapp/.cargo/registry
          ~/webapp/.cargo/git
          webapp/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: |
        trunk build --release
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your desired region

    - name: Upload to S3
      run: |
        echo "Deploying to ${{ steps.env.outputs.environment }} environment..."
        aws s3 sync dist/ s3://${{ steps.env.outputs.bucket }} --delete
